export enum PageSectionKey {
  MEDIA = 'MEDIA',
  BASIC_INFO = 'BASIC_INFO',
  CONTACT = 'CONTACT',
  ADDRESS = 'ADDRESS',
  WORKING_HOURS = 'WORKING_HOURS',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  REVIEWS = 'REVIEWS',
  PACKAGES = 'PACKAGES',
}
